import { LinkedList } from "./linkedList.js";
const vehicle = new LinkedList();
vehicle.append("Lamborghini");
vehicle.prepend("Bugatti");
vehicle.append("Dodge Challenger");
console.log(vehicle.size());
console.log(vehicle.head());
console.log(vehicle.tail());
console.log(vehicle.contains("Dodge Challenger"));
console.log(vehicle.at(1));
vehicle.pop();
console.log(vehicle.contains("Dodge Challenger"));
console.log(vehicle.contains("Ferrari"));
console.log(vehicle.find("Bugatti"));
console.log(vehicle.find("Porsche"));
console.log(vehicle.toString());